force-app/main/default/objects/Industry__c/Industry__c.object-meta.xml
<CustomObject>
    <description>A comprehensive record of all US NAICS (North American Industry Classification System) codes and their respective titles, allowing business accounts to be accurately associated with their correct industry classification.</description>
    <label>Industry</label>
    <nameField>
        <displayFormat>IND-{000000}</displayFormat>
        <label>System Industry Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Industries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Industry__c/fields/NAICS_Code__c.field-meta.xml
<CustomField>
    <fullName>NAICS_Code__c</fullName>
    <description>A unique identifier that aligns a business account with the relevant industry classification as defined by the North American Industry Classification System (NAICS). This standardized code enables precise industry categorization and facilitates accurate business analysis and reporting.</description>
    <inlineHelpText>Enter the NAICS code that matches the classification as defined by the North American Industry Classification System (NAICS).</inlineHelpText>
    <label>NAICS Code</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/LinkNAICSToCompany.cls
public class LinkNAICSToCompany {

    public class CompanyInput {
        @InvocableVariable(label='Company Id')
        public Id companyId;

        @InvocableVariable(label='NAICS Code')
        public String codeNAICS;
    }

    public class LinkNAICSResultFlag {
        @InvocableVariable(label='Established Relationship?')
        public Boolean hasRelationship;
    }

    @InvocableMethod(label='')
    public static List<LinkNAICSResultFlag> linkNAICS(List<CompanyInput> inputs) {
        
        System.debug('linkNAICS has been called');

        // Create lists for our variables
        List<Account> companiesToUpdate = new List<Account>();
        List<LinkNAICSResultFlag> results = new List<LinkNAICSResultFlag>();

        // Loop through the inputs
        for (CompanyInput input : inputs) {
            LinkNAICSResultFlag result = new LinkNAICSResultFlag();
            try {

                // Query for the NAICS records that match the NAICS Code
                Industry__c naics = [SELECT Id FROM Industry__c WHERE NAICS_Code__c = :input.codeNAICS LIMIT 1];

                // If a matching NAICS Industry is located, set the lookup field on the company
                if (naics != null) {
                    Account currentAccount = new Account(Id=input.companyId, Industry_NAICS__c=naics.Id);
                    companiesToUpdate.add(currentAccount);
                    System.debug('Added: ' + currentAccount + 'to companies to update');

                    result.hasRelationship = True; // Set the flag as true
                    results.add(result);
                } else {
                    result.hasRelationship = False; // Set the flag as false
                    results.add(result);
                }
            } catch (Exception e) {
                result.hasRelationship = False; // Set the flag as false
                results.add(result);
                System.debug('Error linking NAICS: ' + e.getMessage());
            }
        }

        // Update the companies if there are any to update
        if (!companiesToUpdate.isEmpty()) {
            UpdateWithExceptions.SafeUpdate(companiesToUpdate);
        }

        return results;
    }
}